package pdfgen

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jung-kurt/gofpdf"

	"github.com/terendelagua/teren-hotels-backend/internal/models"
	"github.com/terendelagua/teren-hotels-backend/pkg/config"
	"github.com/terendelagua/teren-hotels-backend/pkg/pdfstore"
)

// =============================================================================
// Tests for the PDF generator and the local object store. We do NOT mock
// gofpdf — running the real renderer catches regression bugs in the layout.
// For storage we use a tmp dir (LocalStore), not R2, so tests run without
// external credentials.
// =============================================================================

// minimalInvoiceDetail builds a model.InvoiceDetail good enough to drive
// the PDF generator. No DB required.
func minimalInvoiceDetail(t *testing.T) models.InvoiceDetail {
	t.Helper()
	now := time.Now()
	propID := uuid.New()
	bookingID := uuid.New()
	invoiceID := uuid.New()
	userID := uuid.New()

	invoice := models.Invoice{
		ID:               invoiceID,
		PropertyID:       propID,
		BookingID:        bookingID,
		InvoiceNumber:    "INV-TEST-0001",
		Subtotal:         500000,
		TaxAmount:        55000,
		PPNRateSnapshot:  0.11,
		Total:            555000,
		Status:           models.InvoiceStatusActive,
		IssuedAt:         now,
		CreatedBy:        userID,
		CreatedAt:        now,
		UpdatedAt:        now,
		OriginalCurrency: "IDR",
		ExchangeRate:     1.0,
	}

	lineItems := []models.InvoiceLineItem{
		{
			ID:          uuid.New(),
			InvoiceID:   invoiceID,
			Description: "Room 101 - 3 nights",
			Quantity:    3,
			UnitPrice:   166666.67,
			Total:       500000,
			SortOrder:   0,
			CreatedAt:   now,
		},
	}

	return models.InvoiceDetail{
		Invoice:         invoice,
		LineItems:       lineItems,
		Payments:        []models.Payment{},
		TotalPaid:       0,
		TotalRefunded:   0,
		Balance:         555000,
		EffectiveStatus: models.PaymentStatusUnpaid,
	}
}

// TestBuildPDF_ValidHeader asserts the generated bytes start with the PDF
// magic number "%PDF-" (file signature).
func TestBuildPDF_ValidHeader(t *testing.T) {
	d := minimalInvoiceDetail(t)
	bytes, err := buildPDF(d, LabelsFor("en"))
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	if len(bytes) < 8 {
		t.Fatalf("output too short: %d bytes", len(bytes))
	}
	if string(bytes[:5]) != "%PDF-" {
		t.Errorf("missing %%PDF- header, got: %q", string(bytes[:8]))
	}
	if !contains(bytes, []byte("%%EOF")) {
		t.Errorf("missing %%EOF footer")
	}
}

// TestBuildPDF_VoidIncludesWatermark asserts that voiding an invoice
// renders a different (larger) PDF than the active one, due to the
// added VOID marker. We don't grep for the literal "VOID" string
// because gofpdf compresses content streams; the size delta is the
// reliable signal for "extra content was added".
func TestBuildPDF_VoidIncludesWatermark(t *testing.T) {
	d := minimalInvoiceDetail(t)
	active, err := buildPDF(d, LabelsFor("en"))
	if err != nil {
		t.Fatalf("active: %v", err)
	}

	d.Status = models.InvoiceStatusVoid
	voided, err := buildPDF(d, LabelsFor("en"))
	if err != nil {
		t.Fatalf("voided: %v", err)
	}

	// The void PDF should be at least as large as the active one
	// (the VOID marker is an extra text run).
	if len(voided) <= len(active) {
		t.Errorf(
			"voided PDF should be larger than active (got active=%d, void=%d)",
			len(active), len(voided),
		)
	}
}

// TestBuildPDF_RefundedIncludesStamp (v1.2 Block 12) asserts that a
// fully refunded invoice gets the REFUNDED diagonal stamp. We compare
// the bytes against the active baseline AND the void baseline: the
// refunded PDF must be visually different from both (different stamp
// text + the same diagonal stamp machinery).
func TestBuildPDF_RefundedIncludesStamp(t *testing.T) {
	d := minimalInvoiceDetail(t)
	active, err := buildPDF(d, LabelsFor("en"))
	if err != nil {
		t.Fatalf("active: %v", err)
	}

	d.Status = models.InvoiceStatusRefunded
	refunded, err := buildPDF(d, LabelsFor("en"))
	if err != nil {
		t.Fatalf("refunded: %v", err)
	}

	// Refunded PDF is larger than the active baseline (extra stamp).
	if len(refunded) <= len(active) {
		t.Errorf(
			"refunded PDF should be larger than active (got active=%d, refunded=%d)",
			len(active), len(refunded),
		)
	}

	// And visually different from the void PDF (different stamp text).
	d.Status = models.InvoiceStatusVoid
	voided, err := buildPDF(d, LabelsFor("en"))
	if err != nil {
		t.Fatalf("voided: %v", err)
	}
	if len(refunded) == len(voided) && bytesHaveSameSHA(refunded, voided) {
		t.Error("refunded PDF is byte-identical to voided PDF (should differ — different stamp text)")
	}
}

// bytesHaveSameSHA is a tiny helper for byte-equality. Used by the
// RefundedIncludesStamp test to avoid pulling in crypto/sha256
// inline.
func bytesHaveSameSHA(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// TestBuildPDF_RefundedStamp_AllLocales (v1.2 Block 12) asserts that
// the Refunded label is present in every locale the PDF generator
// ships — auditors in es/id/en should see the same diagonal stamp
// treatment.
func TestBuildPDF_RefundedStamp_AllLocales(t *testing.T) {
	d := minimalInvoiceDetail(t)
	d.Status = models.InvoiceStatusRefunded
	for _, locale := range []string{"en", "es", "id"} {
		_, err := buildPDF(d, LabelsFor(locale))
		if err != nil {
			t.Errorf("locale=%s: build: %v", locale, err)
		}
		// Verify the label map carries the Refunded string too —
		// silent fallback would be a UX bug.
		labels := LabelsFor(locale)
		if labels.Refunded == "" {
			t.Errorf("locale=%s: Refunded label missing", locale)
		}
	}
}

// TestLocalStore_PutAndRoundTrip writes a PDF and verifies the URL
// points to the file on disk and the file round-trips.
func TestLocalStore_PutAndRoundTrip(t *testing.T) {
	dir := t.TempDir()
	s, err := pdfstore.NewLocalStore(localConfig(dir))
	if err != nil {
		t.Fatalf("newLocalStore: %v", err)
	}
	url, err := s.Put(context.Background(), "invoices/INV-2026-0001.pdf", []byte("PDF-DATA"))
	if err != nil {
		t.Fatalf("Put: %v", err)
	}
	// URL is built with forward slashes (POSIX style) regardless of OS.
	// We don't compare the URL string directly; we verify the file exists
	// and round-trips, which is what matters.
	_ = url
	got, err := os.ReadFile(filepath.Join(dir, "invoices", "INV-2026-0001.pdf"))
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	if string(got) != "PDF-DATA" {
		t.Errorf("roundtrip: want %q, got %q", "PDF-DATA", got)
	}
}

// TestLocalStore_URLIsHTTPScheme: the URL returned by Put must be a
// same-origin HTTP URL — browsers block file:// from JS, so returning
// one would break the SPA's "Open PDF" button (B7-validation).
func TestLocalStore_URLIsHTTPScheme(t *testing.T) {
	dir := t.TempDir()
	s, _ := pdfstore.NewLocalStore(localConfig(dir))
	url, err := s.Put(context.Background(), "invoices/INV-2026-0001.pdf", []byte("X"))
	if err != nil {
		t.Fatalf("Put: %v", err)
	}
	if !strings.HasPrefix(url, "http://") && !strings.HasPrefix(url, "https://") {
		t.Errorf("expected HTTP URL, got %q", url)
	}
	// Default PDFBaseURL = http://localhost:8080/api/v1/pdfs
	want := "http://localhost:8080/api/v1/pdfs/invoices/INV-2026-0001.pdf"
	if url != want {
		t.Errorf("URL mismatch: want %q, got %q", want, url)
	}
}

// TestLocalStore_CustomPDFBaseURL: a custom PDFBaseURL in config is
// honoured (so production deployments can point at a CDN).
func TestLocalStore_CustomPDFBaseURL(t *testing.T) {
	dir := t.TempDir()
	cfg := localConfig(dir)
	cfg.PDFBaseURL = "https://pdfs.example.com"
	s, _ := pdfstore.NewLocalStore(cfg)
	url, err := s.Put(context.Background(),
		"00000000-0000-0000-0000-000000000000/invoices/INV-1.pdf", []byte("X"))
	if err != nil {
		t.Fatalf("Put: %v", err)
	}
	want := "https://pdfs.example.com/00000000-0000-0000-0000-000000000000/invoices/INV-1.pdf"
	if url != want {
		t.Errorf("URL mismatch: want %q, got %q", want, url)
	}
}

// TestLocalStore_AutoCreatesSubdirs: nested keys (property_id/invoices/...)
// should work without the caller mkdir-ing.
func TestLocalStore_AutoCreatesSubdirs(t *testing.T) {
	dir := t.TempDir()
	s, _ := pdfstore.NewLocalStore(localConfig(dir))
	if _, err := s.Put(context.Background(),
		"00000000-0000-0000-0000-000000000000/invoices/INV-2026-0001.pdf",
		[]byte("X")); err != nil {
		t.Fatalf("Put: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir,
		"00000000-0000-0000-0000-000000000000", "invoices", "INV-2026-0001.pdf")); err != nil {
		t.Errorf("file not created at nested path: %v", err)
	}
}

// TestNewStore_FallsBackToLocalWhenNoR2Creds: if the config has no R2
// credentials, NewStore returns a LocalStore.
func TestNewStore_FallsBackToLocalWhenNoR2Creds(t *testing.T) {
	cfg := localConfig(t.TempDir())
	s, err := pdfstore.NewStore(cfg)
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	if _, ok := s.(*pdfstore.LocalStore); !ok {
		t.Errorf("expected *pdfstore.LocalStore, got %T", s)
	}
}

// TestPdfstoreObjectKey_Format: the object key is {propertyID}/invoices/{number}.pdf.
func TestPdfstoreObjectKey_Format(t *testing.T) {
	propID := uuid.MustParse("11111111-1111-1111-1111-111111111111")
	key := pdfstore.ObjectKey(propID, "INV-2026-0001")
	want := "11111111-1111-1111-1111-111111111111/invoices/INV-2026-0001.pdf"
	if key != want {
		t.Errorf("key: want %s, got %s", want, key)
	}
}

// TestGofpdf_RendersWithoutLogo: smoke test of the underlying lib.
func TestGofpdf_RendersWithoutLogo(t *testing.T) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	pdf.SetFont("Helvetica", "B", 24)
	pdf.Cell(0, 12, "Smoke")
	if err := pdf.Output(&dummyWriter{}); err != nil {
		t.Fatalf("gofpdf output: %v", err)
	}
}

// =============================================================================
// Tests for locale + encoding (B7-validation fix)
// =============================================================================

// TestBuildPDF_UsesEnglishLabels verifies the hardcoded PDF copy is
// in English (not Spanish). We look for the English labels that
// replace the previous Spanish ones. The PDF stream is compressed, so
// we also test the helpers directly.
func TestBuildPDF_UsesEnglishLabels(t *testing.T) {
	d := minimalInvoiceDetail(t)
	bytes, err := buildPDF(d, LabelsFor("en"))
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	if len(bytes) < 500 {
		t.Errorf("PDF suspiciously small: %d bytes", len(bytes))
	}
}

// TestBuildPDF_IndonesianLocale produces a PDF with the Indonesian
// Labels set and verifies the labels map was honoured. We check the
// pdfgen.LabelsFor(...) lookup plus the rendering helpers, because the
// compressed stream hides the actual characters.
func TestBuildPDF_IndonesianLocale(t *testing.T) {
	labels := LabelsFor("id")
	if labels.Title != "FAKTUR" {
		t.Errorf("id labels.Title: want FAKTUR, got %q", labels.Title)
	}
	if labels.Payments != "Pembayaran" {
		t.Errorf("id labels.Payments: want Pembayaran, got %q", labels.Payments)
	}
	if labels.BookingLabel != "Pemesanan" {
		t.Errorf("id labels.BookingLabel: want Pemesanan, got %q", labels.BookingLabel)
	}
	// Spot-check the unknown-tag fallback.
	if l := LabelsFor("xx-YY"); l.Title != "INVOICE" {
		t.Errorf("unknown locale fallback: want INVOICE, got %q", l.Title)
	}
	// Empty tag → English.
	if l := LabelsFor(""); l.Title != "INVOICE" {
		t.Errorf("empty locale fallback: want INVOICE, got %q", l.Title)
	}
}

// TestBuildPDF_SpanishLocale asserts the Spanish label set is
// honoured and that buildPDF doesn't choke on the diacritics in the
// labels (B7-validation 3: sanitize() must be applied to every label
// passed to gofpdf or we'd get mojibake).
func TestBuildPDF_SpanishLocale(t *testing.T) {
	labels := LabelsFor("es")
	if labels.Title != "FACTURA" {
		t.Errorf("es labels.Title: want FACTURA, got %q", labels.Title)
	}
	if labels.Room != "Habitación" {
		t.Errorf("es labels.Room: want Habitación, got %q", labels.Room)
	}
	if labels.Description != "Descripción" {
		t.Errorf("es labels.Description: want Descripción, got %q", labels.Description)
	}
	// Build a PDF with Spanish labels and verify it stays one page.
	d := minimalInvoiceDetail(t)
	bytes, err := buildPDF(d, labels)
	if err != nil {
		t.Fatalf("build es PDF: %v", err)
	}
	if countPDFPages(bytes) != 1 {
		t.Errorf("Spanish PDF should be 1 page")
	}
	// After sanitize, all diacritics fold to ASCII base letters.
	got := sanitize(labels.Room)
	if got != "Habitacion" {
		t.Errorf("sanitize(Habitación): want Habitacion, got %q", got)
	}
}

// TestBuildPDF_NoMojibakeInStream generates a PDF whose line item
// description contains diacritics, then scans the raw PDF bytes for
// the canonical mojibake signatures (Ã followed by a control byte).
// If sanitize() ever stopped working, this test catches it.
func TestBuildPDF_NoMojibakeInStream(t *testing.T) {
	d := minimalInvoiceDetail(t)
	d.LineItems[0].Description = "Habitación Premium — PPN incluido"
	bytes, err := buildPDF(d, LabelsFor("en"))
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	for _, sig := range []string{"\xc3\xb3", "\xc3\xb1", "\xc3\xa9", "\xc2\xb0", "\xc2\xb7"} {
		if contains(bytes, []byte(sig)) {
			t.Errorf("PDF contains mojibake bytes %q — sanitize() failed", sig)
		}
	}
}

// TestSanitize_PureASCII checks the sanitizer strips diacritics and
// non-ASCII chars from arbitrary input, so callers can trust
// `sanitize(x)` is always safe to feed into gofpdf.
func TestSanitize_PureASCII(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"Hello", "Hello"},
		{"Habitación", "Habitacion"},
		{"Übung & Café", "Ubung & Cafe"},
		{"niño", "nino"},
		{"Mr. Smith — Junior", "Mr. Smith - Junior"},
		{`smart "quotes"`, `smart "quotes"`},
		{`‘left’ and ’right’`, `'left' and 'right'`},
		{"emoji 🚀", "emoji ?"},
		{"", ""},
		{"IDR · UTC+8", "IDR - UTC+8"},
		{"UPPERCASE ÁCENTS", "UPPERCASE ACENTS"},
	}
	for _, c := range cases {
		got := sanitize(c.in)
		if got != c.want {
			t.Errorf("sanitize(%q): want %q, got %q", c.in, c.want, got)
		}
	}
}

// TestBuildPDF_PropertyAndGuestInEnglish checks the user-visible
// blocks are in English. Indirect test: confirm sanitize() applied
// to propertyBlock() and guestBlock() produces ASCII-clean strings.
func TestBuildPDF_PropertyAndGuestInEnglish(t *testing.T) {
	d := minimalInvoiceDetail(t)
	labels := LabelsFor("en")
	prop := sanitize(propertyBlock(labels))
	guest := sanitize(guestBlock(d, labels))
	for _, s := range []string{prop, guest} {
		for i, r := range s {
			if r > 0x7F {
				t.Errorf("non-ASCII byte at index %d: %q (full=%q)", i, r, s)
			}
		}
	}
	// And the language is clearly English: "Booking" not "Reserva".
	if !contains([]byte(guest), []byte("Booking:")) {
		t.Errorf("guest block missing 'Booking:' label, got %q", guest)
	}
	if contains([]byte(prop), []byte("FACTURA")) ||
		contains([]byte(prop), []byte("Habitación")) ||
		contains([]byte(prop), []byte("Emitida")) {
		t.Errorf("property block contains Spanish copy: %q", prop)
	}
}

// TestBuildPDF_SinglePageForMinimalInvoice asserts the layout fits in
// one A4 page for a normal invoice (header + 1 line item + 1 payment).
// Before B7-validation 2, the footer was hardcoded at Y=282mm, which
// pushed the page break and produced a 2-page PDF. We check the
// rendered text appears on page 1 — gofpdf emits a "Type /Page"
// pseudo-object per page; the simpler proxy is to count occurrences of
// the page-content header "/Type /Page" minus "/Type /Pages" in the
// byte stream.
func TestBuildPDF_SinglePageForMinimalInvoice(t *testing.T) {
	d := minimalInvoiceDetail(t)
	bytes, err := buildPDF(d, LabelsFor("en"))
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	pageCount := countPDFPages(bytes)
	if pageCount != 1 {
		t.Errorf("expected 1 page, got %d", pageCount)
	}
}

// countPDFPages counts "/Type /Page" occurrences in a PDF byte
// stream, excluding the parent "/Type /Pages" object. This is a
// heuristic but it's accurate for gofpdf's output and avoids pulling
// in a PDF parser for a single layout test.
func countPDFPages(pdf []byte) int {
	const pageObj = "/Type /Page"
	const pagesObj = "/Type /Pages"
	total := bytes.Count(pdf, []byte(pageObj))
	parent := bytes.Count(pdf, []byte(pagesObj))
	return total - parent
}

// =============================================================================
// Helpers
// =============================================================================

func contains(haystack, needle []byte) bool {
	if len(needle) == 0 {
		return true
	}
	for i := 0; i+len(needle) <= len(haystack); i++ {
		match := true
		for j := 0; j < len(needle); j++ {
			if haystack[i+j] != needle[j] {
				match = false
				break
			}
		}
		if match {
			return true
		}
	}
	return false
}

type dummyWriter struct{}

func (d *dummyWriter) Write(p []byte) (int, error) { return len(p), nil }

// localConfig builds a config.Config with no R2 credentials — the
// factory will pick LocalStore.
func localConfig(localDir string) *config.Config {
	return &config.Config{
		LocalPDFDir: localDir,
	}
}
