package pdfgen

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jung-kurt/gofpdf"

	"github.com/terendelagua/teren-hotels-backend/internal/models"
	"github.com/terendelagua/teren-hotels-backend/pkg/config"
	"github.com/terendelagua/teren-hotels-backend/pkg/pdfstore"
)

// =============================================================================
// Tests for the PDF generator and the local object store. We do NOT mock
// gofpdf — running the real renderer catches regression bugs in the layout.
// For storage we use a tmp dir (LocalStore), not R2, so tests run without
// external credentials.
// =============================================================================

// minimalInvoiceDetail builds a model.InvoiceDetail good enough to drive
// the PDF generator. No DB required.
func minimalInvoiceDetail(t *testing.T) models.InvoiceDetail {
	t.Helper()
	now := time.Now()
	propID := uuid.New()
	bookingID := uuid.New()
	invoiceID := uuid.New()
	userID := uuid.New()

	invoice := models.Invoice{
		ID:               invoiceID,
		PropertyID:       propID,
		BookingID:        bookingID,
		InvoiceNumber:    "INV-TEST-0001",
		Subtotal:         500000,
		TaxAmount:        55000,
		PPNRateSnapshot:  0.11,
		Total:            555000,
		Status:           models.InvoiceStatusActive,
		IssuedAt:         now,
		CreatedBy:        userID,
		CreatedAt:        now,
		UpdatedAt:        now,
		OriginalCurrency: "IDR",
		ExchangeRate:     1.0,
	}

	lineItems := []models.InvoiceLineItem{
		{
			ID:          uuid.New(),
			InvoiceID:   invoiceID,
			Description: "Room 101 - 3 nights",
			Quantity:    3,
			UnitPrice:   166666.67,
			Total:       500000,
			SortOrder:   0,
			CreatedAt:   now,
		},
	}

	return models.InvoiceDetail{
		Invoice:         invoice,
		LineItems:       lineItems,
		Payments:        []models.Payment{},
		TotalPaid:       0,
		TotalRefunded:   0,
		Balance:         555000,
		EffectiveStatus: models.PaymentStatusUnpaid,
	}
}

// TestBuildPDF_ValidHeader asserts the generated bytes start with the PDF
// magic number "%PDF-" (file signature).
func TestBuildPDF_ValidHeader(t *testing.T) {
	d := minimalInvoiceDetail(t)
	bytes, err := buildPDF(d)
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	if len(bytes) < 8 {
		t.Fatalf("output too short: %d bytes", len(bytes))
	}
	if string(bytes[:5]) != "%PDF-" {
		t.Errorf("missing %%PDF- header, got: %q", string(bytes[:8]))
	}
	if !contains(bytes, []byte("%%EOF")) {
		t.Errorf("missing %%EOF footer")
	}
}

// TestBuildPDF_VoidIncludesWatermark asserts that voiding an invoice
// renders a different (larger) PDF than the active one, due to the
// added VOID marker. We don't grep for the literal "VOID" string
// because gofpdf compresses content streams; the size delta is the
// reliable signal for "extra content was added".
func TestBuildPDF_VoidIncludesWatermark(t *testing.T) {
	d := minimalInvoiceDetail(t)
	active, err := buildPDF(d)
	if err != nil {
		t.Fatalf("active: %v", err)
	}

	d.Status = models.InvoiceStatusVoid
	voided, err := buildPDF(d)
	if err != nil {
		t.Fatalf("voided: %v", err)
	}

	// The void PDF should be at least as large as the active one
	// (the VOID marker is an extra text run).
	if len(voided) <= len(active) {
		t.Errorf(
			"voided PDF should be larger than active (got active=%d, void=%d)",
			len(active), len(voided),
		)
	}
}

// TestLocalStore_PutAndRoundTrip writes a PDF and verifies the URL
// points to the file on disk and the file round-trips.
func TestLocalStore_PutAndRoundTrip(t *testing.T) {
	dir := t.TempDir()
	s, err := pdfstore.NewLocalStore(localConfig(dir))
	if err != nil {
		t.Fatalf("newLocalStore: %v", err)
	}
	url, err := s.Put(context.Background(), "invoices/INV-2026-0001.pdf", []byte("PDF-DATA"))
	if err != nil {
		t.Fatalf("Put: %v", err)
	}
	// URL is built with forward slashes (POSIX style) regardless of OS.
	// We don't compare the URL string directly; we verify the file exists
	// and round-trips, which is what matters.
	_ = url
	got, err := os.ReadFile(filepath.Join(dir, "invoices", "INV-2026-0001.pdf"))
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	if string(got) != "PDF-DATA" {
		t.Errorf("roundtrip: want %q, got %q", "PDF-DATA", got)
	}
}

// TestLocalStore_AutoCreatesSubdirs: nested keys (property_id/invoices/...)
// should work without the caller mkdir-ing.
func TestLocalStore_AutoCreatesSubdirs(t *testing.T) {
	dir := t.TempDir()
	s, _ := pdfstore.NewLocalStore(localConfig(dir))
	if _, err := s.Put(context.Background(),
		"00000000-0000-0000-0000-000000000000/invoices/INV-2026-0001.pdf",
		[]byte("X")); err != nil {
		t.Fatalf("Put: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir,
		"00000000-0000-0000-0000-000000000000", "invoices", "INV-2026-0001.pdf")); err != nil {
		t.Errorf("file not created at nested path: %v", err)
	}
}

// TestNewStore_FallsBackToLocalWhenNoR2Creds: if the config has no R2
// credentials, NewStore returns a LocalStore.
func TestNewStore_FallsBackToLocalWhenNoR2Creds(t *testing.T) {
	cfg := localConfig(t.TempDir())
	s, err := pdfstore.NewStore(cfg)
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	if _, ok := s.(*pdfstore.LocalStore); !ok {
		t.Errorf("expected *pdfstore.LocalStore, got %T", s)
	}
}

// TestPdfstoreObjectKey_Format: the object key is {propertyID}/invoices/{number}.pdf.
func TestPdfstoreObjectKey_Format(t *testing.T) {
	propID := uuid.MustParse("11111111-1111-1111-1111-111111111111")
	key := pdfstore.ObjectKey(propID, "INV-2026-0001")
	want := "11111111-1111-1111-1111-111111111111/invoices/INV-2026-0001.pdf"
	if key != want {
		t.Errorf("key: want %s, got %s", want, key)
	}
}

// TestGofpdf_RendersWithoutLogo: smoke test of the underlying lib.
func TestGofpdf_RendersWithoutLogo(t *testing.T) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	pdf.SetFont("Helvetica", "B", 24)
	pdf.Cell(0, 12, "Smoke")
	if err := pdf.Output(&dummyWriter{}); err != nil {
		t.Fatalf("gofpdf output: %v", err)
	}
}

// =============================================================================
// Helpers
// =============================================================================

func contains(haystack, needle []byte) bool {
	if len(needle) == 0 {
		return true
	}
	for i := 0; i+len(needle) <= len(haystack); i++ {
		match := true
		for j := 0; j < len(needle); j++ {
			if haystack[i+j] != needle[j] {
				match = false
				break
			}
		}
		if match {
			return true
		}
	}
	return false
}

type dummyWriter struct{}

func (d *dummyWriter) Write(p []byte) (int, error) { return len(p), nil }

// localConfig builds a config.Config with no R2 credentials — the
// factory will pick LocalStore.
func localConfig(localDir string) *config.Config {
	return &config.Config{
		LocalPDFDir: localDir,
	}
}
